### ISSUE TITLE
JHipster

### ISSUE THREAD

**Issue by AnonymFx** [AnonymFox/foospal-architecture#1]
Check out **JHipster** to generate basic classes and APIs for the server side of the application.

**Comment by Krillian111** [comment]
I tried **JHipster** and created a web application with it. It's relatively straightforward.
After some tweaks I also managed to integrate **Kotlin** code into it. I have a sample project with a RestController and the corresponding DTO written in Kotlin, rest in **Java**. I could create a separate branch with the sample code, just so we have something to try stuff out with.

**Comment by AnonymFx** [comment]
Good idea. I'll just quickly add you to the project now that I know your username ;)

**Comment by Krillian111** [comment]
Uploaded it in the branch "JHipsterKotlinTest". I didn't manage to get annotation based dependency injection working. In Java it works fine, in Kotlin it doesn't, further work is necessary.

**Comment by Krillian111** [comment]
Seems like I didnt copy all files properly, gotta fix some errors so that everyone can just import the project in IntelliJ without any issues.

**Comment by Krillian111** [comment]
Okay, in order to make it work in IntelliJ I had to add the KotlinJavaRuntime under "File -> Project Structure -> Project Settings -> Modules -> '+'-Symbol -> Kotlin(Java)". Could start it up with gradlew after that, let me know if it works for you.
